### PR TITLE
Fix crash in mitmweb when no explicit Server-Connection is logged

### LINKED ISSUE #7733: Frontend Crash on Connection-Tab if no explicite Server-Connection logged
### Problem Description

If to a logged entery the Server-Connection entry is Missing the Frontend Crashes while trying to open the Connection Tab.

#### Steps to reproduce the behavior:
1. Load the attached flow
2. Try to open the Connection-Tab on the A or AAAA entry (See Timings-Tab to chekcif a Server Connection is logged)

[flows.txt](https://github.com/user-attachments/files/20459873/flows.txt)

Flow is generated by mitmweb in wireguard mode.

Additionaly: The console in the browser logs: "e is null" (i guess the Server-Information) 
Browser: Firefox 128.10.0esr (64-Bit)

### System Information

```raw
Mitmproxy: 12.1.0 binary
Python: 3.13.3
OpenSSL: OpenSSL 3.4.1 11 Feb 2025
Platform: Linux-6.1.0-37-amd64-x86_64-with-glibc2.36
```

### Checklist

- [x] This bug affects the [latest mitmproxy release](https://github.com/mitmproxy/mitmproxy/releases).

### PR DESCRIPTION
**Pull request by lups2000**
#### Description

Fixes: #7733 

#### Checklist

 - [x] I have updated tests where applicable.
 - [x] I have added an entry to the CHANGELOG.

### CODE REVIEW

File: web/src/js/components/FlowView/Connection.tsx [hunk 1]
```diff
@@ -8,9 +8,9 @@ type ConnectionInfoProps = {
 
 export function formatAddress(
     desc: string,
-    address: Address | undefined,
+    address: Address | undefined | null,
 ): React.ReactElement {
-    if (address === undefined) {
+    if (address === undefined || address === null) {
```
Comment (mhils) [inline web/src/js/components/FlowView/Connection.tsx:13]:
```suggestion
    if (!address) {
```
(in contrast to the flow reducer changes, here we don't care about the difference at all)

**Review by mhils — APPROVED** [review]
Thanks! LGTM % nit
